#this is am empty workflow for demonstration in class
name: ci 
on:
  push:
     branches: [develop]
jobs:
   test:
       runs-on: ubuntu-latest
       steps:
         - name: checkout
           uses: actions/checkout@v6
         - name: Set up Node.js
           uses: actions/setup-node@v2
           with:
             node-version: '14'
         - name: Install dependencies
           run: npm install
         - name: Run tests
           run: npm test
